INSERT INTO lesson_category (category_name) VALUES 
('HTML'), 
('CSS');


INSERT INTO lesson (lesson_name, lesson_order, category_name) VALUES
('HTML_Introduction', 1, 'HTML'),
('HTML_Editors', 2, 'HTML'),
('HTML_Basic', 3, 'HTML'),
('HTML_Elements', 4, 'HTML'),
('HTML_Attributes', 5, 'HTML'),
('HTML_Headings', 6, 'HTML'),
('HTML_Paragraphs', 7, 'HTML'),
('HTML_Styles', 8, 'HTML'),
('HTML_Formatting', 9, 'HTML'),
('HTML_Quotations', 10, 'HTML'),
('HTML_Comments', 11, 'HTML'),
('HTML_Colors', 12, 'HTML'),
('HTML_CSS', 13, 'HTML'),
('HTML_Links', 14, 'HTML'),
('HTML_Images', 15, 'HTML'),
('HTML_Favicon', 16, 'HTML'),
('HTML_Page_Title', 17, 'HTML'),
('HTML_Tables', 18, 'HTML'),
('HTML_Lists', 19, 'HTML'),
('HTMLBlock&_Inline', 20, 'HTML'),
('HTML_Div', 21, 'HTML'),
('HTML_Classes', 22, 'HTML');

INSERT INTO lesson (lesson_name, lesson_order, category_name) VALUES
('CSS_Introduction', 1, 'CSS'),
('CSS_Syntax', 2, 'CSS'),
('CSS_Selectors', 3, 'CSS'),
('CSS_How_To', 4, 'CSS'),
('CSS_Comments', 5, 'CSS'),
('CSS_Colors', 6, 'CSS'),
('CSS_Backgrounds', 7, 'CSS'),
('CSS_Borders', 8, 'CSS'),
('CSS_Margins', 9, 'CSS'),
('CSS_Padding', 10, 'CSS'),
('CSS_Height/Width', 11, 'CSS'),
('CSS_Box_Model', 12, 'CSS'),
('CSS_Text', 13, 'CSS'),
('CSS_Fonts', 14, 'CSS'),
('CSS_Links', 15, 'CSS'),
('CSS_Lists', 16, 'CSS'),
('CSS_Tables', 17, 'CSS'),
('CSS_Display', 18, 'CSS'),
('CSS_Position', 19, 'CSS'),
('CSS_Float', 20, 'CSS'),
('CSS_Pseudo-classes', 21, 'CSS'),
('CSS_Pseudo-elements', 22, 'CSS'),
('CSS_Flexbox', 23, 'CSS'),
('CSS_Grid', 24, 'CSS');